sudo: false

language: python

matrix:
  include:
    - os: linux
      python: pypy
    - os: linux
      python: 2.7
    - os: osx
      language: generic
      sudo: required

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew update || brew update;
      brew outdated pyenv || brew upgrade pyenv;
    fi

install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      export PATH="~/.pyenv/bin:$PATH";
      eval "$(pyenv init -)";
      eval "$(pyenv virtualenv-init -)";
      pyenv versions
      pyenv install pypy-5.6.0;
      pyenv global system pypy-5.6.0;
      pyenv versions
    fi
  - which python
  - which pypy
  - pip install -U pip
  - pip install tox tox-travis
  - which tox
  - pip install -e .[development]

script: tox

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
    - develop
