sudo: false

matrix:
  include:
    - os: osx
      sudo: required
      language: generic

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew update || brew update;
      brew outdated pyenv || brew upgrade pyenv;
    fi

install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      pyenv install 2.7.13;
      pyenv global 2.7.11;
      pyenv install pypy-5.6.0;
      pyenv global pypy-5.6.0;
    fi
  - which python
  - pip install -U pip
  - pip install tox tox-travis
  - which tox
  - pip install -e .[development]

script: tox

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
    - develop
